# Generated by Django 4.2.8 on 2023-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tasks", "0002_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
