# Generated by Django 4.2.8 on 2023-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tasks', '0003_post_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1),
        ),
    ]
