# Generated by Django 4.2.8 on 2023-12-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tasks', '0004_post_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['done']},
        ),
    ]
