# Generated by Django 4.2.8 on 2023-12-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tasks', '0005_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
