# Generated by Django 4.2.8 on 2023-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tasks", "0007_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
