# Generated by Django 4.2.8 on 2023-12-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tasks', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
