# Generated by Django 4.2.8 on 2023-12-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_tasks", "0010_remove_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="due_date",
            field=models.DateField(),
        ),
    ]
